### ISSUE TITLE
Refactor `meta` section of pds4+json and pds4+xml to use ops namespace

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#154]
## 💡 Description

The flattened `ops` attributes are in the metadata (e.g. `ops:Data_File_Info.ops:creation_date_time`).

Then it looks like it is being translated / renamed into the API, e.g. for pds4+json response:
```json
      "meta": {
        "node_name": "PDS_ENG",
        "label_file": {
          "file_name": "bundle_ovirs.xml",
          "file_ref": "/data/pds4/test-data/registry/orex.ovirs/bundle_ovirs.xml",
          "creation_date": "2021-02-22T22:57:56Z",
          "file_size": "11302",
          "md5_checksum": "b7405a8e071d84a521e73c451399a2a5"
        }
```

Instead, we should keep that namespace as-is, and create the JSON Objects to mimic our `ops` data model. This should not be custom code for each attribute, but instead something generic that just parses out the `ops:` attributes, and outputs into the `meta` object. We may be adding/removing/renaming `ops:` attributes over time, so we don't want to have to update the API code every time that happens. , e.g.

```
      "ops:Data_File_Info.ops:md5_checksum",
      "ops:Label_File_Info.ops:creation_date_time",
      "ops:Foo.ops:bar"
```
becomes
```json
      "meta": {
        "ops:Data_File_Info": {
             "ops:md5_checksum": [ "b7405a8e071d84a521e73c451399a2a5" ]
        }
        "ops:Label_File_Info": {
             "ops:creation_date_time": [ "2021-02-22T22:57:56Z" ]
        }
        "ops:Foo": {
             "ops:bar": [ "baz" ]
        }
```

Similarly, we should map this to XML in the pds4+xml response.

## Related requirements
🦄 #125 
🦄 #101

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

I think this means that you want to modify the swaggerhub spec (yaml) to have Pds4Metadata represent what you are looking for. Currently it is:

```
    pds4Metadata:
      type: object
      properties:
        node_name:
          type: string
        label_file:
          type: object
          properties:
            file_name:
              type: string
            file_ref:
              type: string
            creation_date:
              type: string
            file_size:
              type: string
            md5_checksum:
              type: string        
        data_files:
          type: array
          items:
            type: object
            properties:
              file_name:
                type: string
              file_ref:
                type: string
              creation_date:
                type: string
              file_size:
                type: string
              md5_checksum:
                type: string
              mime_type:
                type: string
```

Now you want it to be more like:

```
    pds4Metadata:
      type: object
      properties:
        ops.Label_File_Info:
          type: object
          properties:
            ops.file_name:
              type: string
            ops.file_ref:
              type: string
            ops.creation_date:
              type: string
            ops.file_size:
              type: string
            ops.md5_checksum:
              type: string        
        ops.Data_File_Info:
          type: array
          items:
            type: object
            properties:
              ops.file_name:
                type: string
              ops.file_ref:
                type: string
              ops.creation_date:
                type: string
              ops.file_size:
                type: string
              ops.md5_checksum:
                type: string
              ops.mime_type:
                type: string
```

Is that what you are looking for or did you want something else?

Not sure how `ops.Foo` maps into swaggerhub. Is that the `node_name` that got lost?

**Comment by jordanpadams** [comment]
@al-niessner the `ops.Foo` is a general example that we can continue to expand the `ops` namespace with more content. I actually propose that we generalize this section of the output similar to what we do with the `pds4` objects in the `pds4+json` and `pds+xml` responses. e.g.

```yaml
        metadata:
          type: object
          description: | 
              Meta information for the PDS product including file system 
              metadata, tracking information, etc.
```

I think down the road we can more strongly type what appears in the section by auto-generating the YAML from the data model, but I don't think we are there yet.

Thoughts? @tloubrieu-jpl

**Comment by tloubrieu-jpl** [comment]
@jordanpadams will add an example for XML

**Comment by tloubrieu-jpl** [comment]
@jordanpadams , @al-niessner , Since PR https://github.com/NASA-PDS/registry-api/pull/82 the content of the meta tag has not prefix space (then not defined namespace ). This is not fully right but we did not meant to improve that before this ticket does it.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl @al-niessner where are we at with this one? am I on the hook for something?

**Comment by jordanpadams** [comment]
as a clarification of above, per conversations we had at a breakout, we want this for the meta section for both JSON and XML:
```
    pds4Metadata:
      type: object
      properties:
        ops.Label_File_Info:
          type: object
          properties:
            ops.file_name:
              type: string
            ops.file_ref:
              type: string
            ops.creation_date:
              type: string
            ops.file_size:
              type: string
            ops.md5_checksum:
              type: string        
        ops.Data_File_Info:
          type: array
          items:
            type: object
            properties:
              ops.file_name:
                type: string
              ops.file_ref:
                type: string
              ops.creation_date:
                type: string
              ops.file_size:
                type: string
              ops.md5_checksum:
                type: string
              ops.mime_type:
                type: string
```
